global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "autocapture"
    static_configs:
      - targets:
          - "host.docker.internal:9005"
  - job_name: "gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:8010"
  - job_name: "graph"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:8020"
